# Generated by Django 4.1.7 on 2023-04-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
