# Generated by Django 4.1.7 on 2023-04-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_report_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updowntime',
            name='status_expected',
        ),
    ]
